### ISSUE TITLE
DemandAnalyzer - Heatmap

### ISSUE THREAD

**Issue by yamidibarra** [DrafProject/draf#5]
Dear @mfleschutz 
I want to analyze the gas demand and would like to know how to change the color of the heatmap. I have checked the function "heatmap" in plotting/scen_plotting. cmap is defined as "OrRd".  The color should differentiate between electricity, heat and gas. Is this possible?

[https://github.com/yamidibarra/Stadt_OG/blob/yamidibarra-patch-1/Case_Study_Windschl%C3%A4g_2019%20(1).ipynb](url)

**Comment by mfleschutz** [comment]
Hi Yami,

Thanks for the feedback. In the `heatmap` function, colormaps can be set using the `cmap` argument. But for this, the `divergingNorm` argument must be set to False to pretend overwriting.

I hope that solves the issue. I will try to clarify this in the documentation soon.
Best regards,
Markus
