### ISSUE TITLE
DemandAnalyzer - analyze_demand

### ISSUE THREAD

**Issue by yamidibarra** [DrafProject/draf#6]
Hi @mfleschutz 

I am using the analyze_demand method defined in the scenario class which generates the plots of violin, load curves etc. This method is linked to the DemandAnalyzer class in which the plots are generated.

I have problems when I analyze the heat demand, because the y-axis shows "P_el" and I would like to change the label of this axis to P_th. Is this possible? is it also posible to change the color of the violin plots?

**Comment by mfleschutz** [comment]
I added a `ylabel` argument to the `analyze_demand` function. With the current version of draf this should work now.

**Comment by mfleschutz** [comment]
Done. @yamidibarra , again, please check if it also works for the show_peaks function.

**Comment by yamidibarra** [comment]
Thank you @mfleschutz! it works. 
Just to show an example, here is the code how it should be implemented:

`da = sc.analyze_demand(demand_waerme, ylabel='P_th (kW)')
pla = da.show_peaks(target_percentile=98, c_EG_peak=50.0)
sc.plot.heatmap(demand_waerme, title='Heat Demand' , divergingNorm= False, cmap='OrRd');` 

`ylabel ` argument must be only 
defined in function analyze_demand.

![show_peaks](https://github.com/DrafProject/draf/assets/66751598/aafcfe59-2b5a-4d4d-8780-a4fd34feae31)
