### ISSUE TITLE
component_templates - EG

### ISSUE THREAD

**Issue by yamidibarra** [DrafProject/draf#7]
Hello @mfleschutz! 

I want to add the EG component and I got this error: 
HTTPError: 403 Client Error: Forbidden for url: [https://transparency.entsoe.eu/api?documentType=A44&in_Domain=10Y1001A1001A82H&out_Domain=10Y1001A1001A82H&securityToken=YOUR_ENTSOE_KEY&periodStart=201812312300&periodEnd=201912312300
](url)

I don´t want to show the whole error log so I leave my notebook here in case you want to take a closer look on the error.

file: Case_Study_Windschläg

[https://github.com/yamidibarra/Stadt_OG/tree/yamidibarra-patch-1](url)

As far as I understood, entsoe does not allow to read data from its website.
is this correct? 

Thanks for your help!

**Comment by mfleschutz** [comment]
The EG compontent uses the elmada module to get day ahead market prices and carbon emission factors mainly from ENTSO-E. For it to work, you need a valid ENTSO-E API key, see Number 9 of https://github.com/DrafProject/draf#quick-start. This involves sending an email to Entsoe, receiving an API key, and storing the key using `elmada.set_api_keys(entsoe="YOUR_ENTSOE_KEY")` where YOUR_ENTSOE_KEY needs to be replaced with the actual key. If you don't need the elmada module, you can still build your own EG component based on the existing component in https://github.com/DrafProject/draf/blob/main/draf/components/component_templates.py.

**Comment by yamidibarra** [comment]
I have requested an API key and followed the steps. However I do not have access to the Entsoe platform. I requested another API with another email and it didn't work either. I waited for the weekend, thinking that maybe I didn't have active access but 3 days later it didn't work. 

When I open the page it shows me: "Please be informed that the legacy REST API endpoint in no longer supported. Only new REST API endpoint is now supported by Transparency Platform". 
I am not clear what is the difference between these two APIs and also since when this update was made. Maybe this is the cause of the error?

**Comment by mfleschutz** [comment]
Good hint. It looks like the cause. We should investigate how to access the new API. This should be an issue for https://github.com/EnergieID/entsoe-py as well.

**Comment by yamidibarra** [comment]
Hello @mfleschutz 

I took a look at entsoe-py.
The entsoe version automatically installed by Draf is V0.2.10. However the latest version is V0.5.10. 
To solve this issue it would be enough to update the entsoe-py version as recommended in: 
https://github.com/EnergieID/entsoe-py/issues/248
